//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.05 at 06:19:25 PM MSK 
//


package ru.telda.dds_01_integration_service.soap_service.integration;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for Card112Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Card112Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nEmergencyCardId" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nCardState" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dtCreate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dtIncident" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lHasCard02" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lHasCard03" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lHasCard04" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lHasCardAT" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lHasCardCommServ" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="nEmergencyCard01" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dtCreate01" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dtIncident01" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="strDeclarant01" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nCard02SyntheticState" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dtCreate02" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dtIncident02" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="strDeclarant02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strNom02" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nCard03SyntheticState" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dtCreate03" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dtIncident03" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="strDeclarant03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strNom03" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nCard04SyntheticState" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dtCreate04" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dtIncident04" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="strDeclarant04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strNom04" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nCardATSyntheticState" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dtCreateAT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dtIncidentAT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="strDeclarantAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strNomAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nCardCommServSyntheticState" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="dtCreateCommServ" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dtIncidentCommServ" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="strDeclarantCommServ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strNomCommServ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strCdPN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strCgPN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strCreator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strPhoneOwner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nSUBRFID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nTOWNID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nTOPONIMID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nRAIONID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nGEONIMID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="strAddressString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strBuilding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strCorps" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strRoom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strAdditionalLocationInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strEntrance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strEntranceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strStoreys" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strIncidentDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nIncidentTypeID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="strCallerContactPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strDeclarantName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strDeclarantLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strDeclarantMiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strDeclarantBuildingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nDeclarantSUBRFID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nDeclarantTOWNID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nDeclarantTOPONIMID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nDeclarantRAIONID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nDeclarantGEONIMID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="strDeclarantAddressString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strDeclarantCorps" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strDeclarantFlat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="geoLatitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="geoLongitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="declarantGeoLatitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="declarantGeoLongitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="callId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="strLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lNear" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="strKm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nCasualties" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="lHumanThreat" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="strCharacter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="srtCondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nNumberStoreys" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nGaz" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="nTime" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="strRepercussion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nPeople" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Card112Type", propOrder = {
    "nEmergencyCardId",
    "nCardState",
    "dtCreate",
    "dtIncident",
    "lHasCard02",
    "lHasCard03",
    "lHasCard04",
    "lHasCardAT",
    "lHasCardCommServ",
    "nEmergencyCard01",
    "dtCreate01",
    "dtIncident01",
    "strDeclarant01",
    "nCard02SyntheticState",
    "dtCreate02",
    "dtIncident02",
    "strDeclarant02",
    "strNom02",
    "nCard03SyntheticState",
    "dtCreate03",
    "dtIncident03",
    "strDeclarant03",
    "strNom03",
    "nCard04SyntheticState",
    "dtCreate04",
    "dtIncident04",
    "strDeclarant04",
    "strNom04",
    "nCardATSyntheticState",
    "dtCreateAT",
    "dtIncidentAT",
    "strDeclarantAT",
    "strNomAT",
    "nCardCommServSyntheticState",
    "dtCreateCommServ",
    "dtIncidentCommServ",
    "strDeclarantCommServ",
    "strNomCommServ",
    "strCdPN",
    "strCgPN",
    "strCreator",
    "strPhoneOwner",
    "nsubrfid",
    "ntownid",
    "ntoponimid",
    "nraionid",
    "ngeonimid",
    "strAddressString",
    "strBuilding",
    "strCorps",
    "strRoom",
    "strAdditionalLocationInfo",
    "strEntrance",
    "strEntranceCode",
    "strStoreys",
    "strIncidentDescription",
    "nIncidentTypeID",
    "strCallerContactPhone",
    "strDeclarantName",
    "strDeclarantLastName",
    "strDeclarantMiddleName",
    "strDeclarantBuildingNumber",
    "nDeclarantSUBRFID",
    "nDeclarantTOWNID",
    "nDeclarantTOPONIMID",
    "nDeclarantRAIONID",
    "nDeclarantGEONIMID",
    "strDeclarantAddressString",
    "strDeclarantCorps",
    "strDeclarantFlat",
    "geoLatitude",
    "geoLongitude",
    "declarantGeoLatitude",
    "declarantGeoLongitude",
    "callId",
    "strLanguage",
    "lNear",
    "strKm",
    "nCasualties",
    "lHumanThreat",
    "strCharacter",
    "srtCondition",
    "nNumberStoreys",
    "nGaz",
    "nTime",
    "strRepercussion",
    "nPeople"
})
public class Card112Type {

    protected BigInteger nEmergencyCardId;
    protected BigInteger nCardState;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtCreate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtIncident;
    protected Boolean lHasCard02;
    protected Boolean lHasCard03;
    protected Boolean lHasCard04;
    protected Boolean lHasCardAT;
    protected Boolean lHasCardCommServ;
    protected BigInteger nEmergencyCard01;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtCreate01;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtIncident01;
    protected String strDeclarant01;
    protected BigInteger nCard02SyntheticState;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtCreate02;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtIncident02;
    protected String strDeclarant02;
    protected String strNom02;
    protected BigInteger nCard03SyntheticState;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtCreate03;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtIncident03;
    protected String strDeclarant03;
    protected String strNom03;
    protected BigInteger nCard04SyntheticState;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtCreate04;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtIncident04;
    protected String strDeclarant04;
    protected String strNom04;
    protected BigInteger nCardATSyntheticState;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtCreateAT;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtIncidentAT;
    protected String strDeclarantAT;
    protected String strNomAT;
    protected BigInteger nCardCommServSyntheticState;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtCreateCommServ;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dtIncidentCommServ;
    protected String strDeclarantCommServ;
    protected String strNomCommServ;
    protected String strCdPN;
    protected String strCgPN;
    protected String strCreator;
    protected String strPhoneOwner;
    @XmlElement(name = "nSUBRFID")
    protected BigInteger nsubrfid;
    @XmlElement(name = "nTOWNID")
    protected BigInteger ntownid;
    @XmlElement(name = "nTOPONIMID")
    protected BigInteger ntoponimid;
    @XmlElement(name = "nRAIONID")
    protected BigInteger nraionid;
    @XmlElement(name = "nGEONIMID")
    protected BigInteger ngeonimid;
    protected String strAddressString;
    protected String strBuilding;
    protected String strCorps;
    protected String strRoom;
    protected String strAdditionalLocationInfo;
    protected String strEntrance;
    protected String strEntranceCode;
    protected String strStoreys;
    protected String strIncidentDescription;
    protected BigInteger nIncidentTypeID;
    protected String strCallerContactPhone;
    protected String strDeclarantName;
    protected String strDeclarantLastName;
    protected String strDeclarantMiddleName;
    protected String strDeclarantBuildingNumber;
    protected BigInteger nDeclarantSUBRFID;
    protected BigInteger nDeclarantTOWNID;
    protected BigInteger nDeclarantTOPONIMID;
    protected BigInteger nDeclarantRAIONID;
    protected BigInteger nDeclarantGEONIMID;
    protected String strDeclarantAddressString;
    protected String strDeclarantCorps;
    protected String strDeclarantFlat;
    protected String geoLatitude;
    protected String geoLongitude;
    protected String declarantGeoLatitude;
    protected String declarantGeoLongitude;
    protected String callId;
    protected String strLanguage;
    protected BigInteger lNear;
    protected String strKm;
    protected BigInteger nCasualties;
    protected BigInteger lHumanThreat;
    protected String strCharacter;
    protected String srtCondition;
    protected BigInteger nNumberStoreys;
    protected BigInteger nGaz;
    protected BigInteger nTime;
    protected String strRepercussion;
    protected BigInteger nPeople;

    /**
     * Gets the value of the nEmergencyCardId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNEmergencyCardId() {
        return nEmergencyCardId;
    }

    /**
     * Sets the value of the nEmergencyCardId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNEmergencyCardId(BigInteger value) {
        this.nEmergencyCardId = value;
    }

    /**
     * Gets the value of the nCardState property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNCardState() {
        return nCardState;
    }

    /**
     * Sets the value of the nCardState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNCardState(BigInteger value) {
        this.nCardState = value;
    }

    /**
     * Gets the value of the dtCreate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtCreate() {
        return dtCreate;
    }

    /**
     * Sets the value of the dtCreate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtCreate(XMLGregorianCalendar value) {
        this.dtCreate = value;
    }

    /**
     * Gets the value of the dtIncident property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtIncident() {
        return dtIncident;
    }

    /**
     * Sets the value of the dtIncident property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtIncident(XMLGregorianCalendar value) {
        this.dtIncident = value;
    }

    /**
     * Gets the value of the lHasCard02 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLHasCard02() {
        return lHasCard02;
    }

    /**
     * Sets the value of the lHasCard02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLHasCard02(Boolean value) {
        this.lHasCard02 = value;
    }

    /**
     * Gets the value of the lHasCard03 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLHasCard03() {
        return lHasCard03;
    }

    /**
     * Sets the value of the lHasCard03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLHasCard03(Boolean value) {
        this.lHasCard03 = value;
    }

    /**
     * Gets the value of the lHasCard04 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLHasCard04() {
        return lHasCard04;
    }

    /**
     * Sets the value of the lHasCard04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLHasCard04(Boolean value) {
        this.lHasCard04 = value;
    }

    /**
     * Gets the value of the lHasCardAT property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLHasCardAT() {
        return lHasCardAT;
    }

    /**
     * Sets the value of the lHasCardAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLHasCardAT(Boolean value) {
        this.lHasCardAT = value;
    }

    /**
     * Gets the value of the lHasCardCommServ property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLHasCardCommServ() {
        return lHasCardCommServ;
    }

    /**
     * Sets the value of the lHasCardCommServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLHasCardCommServ(Boolean value) {
        this.lHasCardCommServ = value;
    }

    /**
     * Gets the value of the nEmergencyCard01 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNEmergencyCard01() {
        return nEmergencyCard01;
    }

    /**
     * Sets the value of the nEmergencyCard01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNEmergencyCard01(BigInteger value) {
        this.nEmergencyCard01 = value;
    }

    /**
     * Gets the value of the dtCreate01 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtCreate01() {
        return dtCreate01;
    }

    /**
     * Sets the value of the dtCreate01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtCreate01(XMLGregorianCalendar value) {
        this.dtCreate01 = value;
    }

    /**
     * Gets the value of the dtIncident01 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtIncident01() {
        return dtIncident01;
    }

    /**
     * Sets the value of the dtIncident01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtIncident01(XMLGregorianCalendar value) {
        this.dtIncident01 = value;
    }

    /**
     * Gets the value of the strDeclarant01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarant01() {
        return strDeclarant01;
    }

    /**
     * Sets the value of the strDeclarant01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarant01(String value) {
        this.strDeclarant01 = value;
    }

    /**
     * Gets the value of the nCard02SyntheticState property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNCard02SyntheticState() {
        return nCard02SyntheticState;
    }

    /**
     * Sets the value of the nCard02SyntheticState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNCard02SyntheticState(BigInteger value) {
        this.nCard02SyntheticState = value;
    }

    /**
     * Gets the value of the dtCreate02 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtCreate02() {
        return dtCreate02;
    }

    /**
     * Sets the value of the dtCreate02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtCreate02(XMLGregorianCalendar value) {
        this.dtCreate02 = value;
    }

    /**
     * Gets the value of the dtIncident02 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtIncident02() {
        return dtIncident02;
    }

    /**
     * Sets the value of the dtIncident02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtIncident02(XMLGregorianCalendar value) {
        this.dtIncident02 = value;
    }

    /**
     * Gets the value of the strDeclarant02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarant02() {
        return strDeclarant02;
    }

    /**
     * Sets the value of the strDeclarant02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarant02(String value) {
        this.strDeclarant02 = value;
    }

    /**
     * Gets the value of the strNom02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNom02() {
        return strNom02;
    }

    /**
     * Sets the value of the strNom02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNom02(String value) {
        this.strNom02 = value;
    }

    /**
     * Gets the value of the nCard03SyntheticState property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNCard03SyntheticState() {
        return nCard03SyntheticState;
    }

    /**
     * Sets the value of the nCard03SyntheticState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNCard03SyntheticState(BigInteger value) {
        this.nCard03SyntheticState = value;
    }

    /**
     * Gets the value of the dtCreate03 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtCreate03() {
        return dtCreate03;
    }

    /**
     * Sets the value of the dtCreate03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtCreate03(XMLGregorianCalendar value) {
        this.dtCreate03 = value;
    }

    /**
     * Gets the value of the dtIncident03 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtIncident03() {
        return dtIncident03;
    }

    /**
     * Sets the value of the dtIncident03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtIncident03(XMLGregorianCalendar value) {
        this.dtIncident03 = value;
    }

    /**
     * Gets the value of the strDeclarant03 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarant03() {
        return strDeclarant03;
    }

    /**
     * Sets the value of the strDeclarant03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarant03(String value) {
        this.strDeclarant03 = value;
    }

    /**
     * Gets the value of the strNom03 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNom03() {
        return strNom03;
    }

    /**
     * Sets the value of the strNom03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNom03(String value) {
        this.strNom03 = value;
    }

    /**
     * Gets the value of the nCard04SyntheticState property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNCard04SyntheticState() {
        return nCard04SyntheticState;
    }

    /**
     * Sets the value of the nCard04SyntheticState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNCard04SyntheticState(BigInteger value) {
        this.nCard04SyntheticState = value;
    }

    /**
     * Gets the value of the dtCreate04 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtCreate04() {
        return dtCreate04;
    }

    /**
     * Sets the value of the dtCreate04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtCreate04(XMLGregorianCalendar value) {
        this.dtCreate04 = value;
    }

    /**
     * Gets the value of the dtIncident04 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtIncident04() {
        return dtIncident04;
    }

    /**
     * Sets the value of the dtIncident04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtIncident04(XMLGregorianCalendar value) {
        this.dtIncident04 = value;
    }

    /**
     * Gets the value of the strDeclarant04 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarant04() {
        return strDeclarant04;
    }

    /**
     * Sets the value of the strDeclarant04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarant04(String value) {
        this.strDeclarant04 = value;
    }

    /**
     * Gets the value of the strNom04 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNom04() {
        return strNom04;
    }

    /**
     * Sets the value of the strNom04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNom04(String value) {
        this.strNom04 = value;
    }

    /**
     * Gets the value of the nCardATSyntheticState property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNCardATSyntheticState() {
        return nCardATSyntheticState;
    }

    /**
     * Sets the value of the nCardATSyntheticState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNCardATSyntheticState(BigInteger value) {
        this.nCardATSyntheticState = value;
    }

    /**
     * Gets the value of the dtCreateAT property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtCreateAT() {
        return dtCreateAT;
    }

    /**
     * Sets the value of the dtCreateAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtCreateAT(XMLGregorianCalendar value) {
        this.dtCreateAT = value;
    }

    /**
     * Gets the value of the dtIncidentAT property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtIncidentAT() {
        return dtIncidentAT;
    }

    /**
     * Sets the value of the dtIncidentAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtIncidentAT(XMLGregorianCalendar value) {
        this.dtIncidentAT = value;
    }

    /**
     * Gets the value of the strDeclarantAT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantAT() {
        return strDeclarantAT;
    }

    /**
     * Sets the value of the strDeclarantAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantAT(String value) {
        this.strDeclarantAT = value;
    }

    /**
     * Gets the value of the strNomAT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNomAT() {
        return strNomAT;
    }

    /**
     * Sets the value of the strNomAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNomAT(String value) {
        this.strNomAT = value;
    }

    /**
     * Gets the value of the nCardCommServSyntheticState property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNCardCommServSyntheticState() {
        return nCardCommServSyntheticState;
    }

    /**
     * Sets the value of the nCardCommServSyntheticState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNCardCommServSyntheticState(BigInteger value) {
        this.nCardCommServSyntheticState = value;
    }

    /**
     * Gets the value of the dtCreateCommServ property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtCreateCommServ() {
        return dtCreateCommServ;
    }

    /**
     * Sets the value of the dtCreateCommServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtCreateCommServ(XMLGregorianCalendar value) {
        this.dtCreateCommServ = value;
    }

    /**
     * Gets the value of the dtIncidentCommServ property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtIncidentCommServ() {
        return dtIncidentCommServ;
    }

    /**
     * Sets the value of the dtIncidentCommServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtIncidentCommServ(XMLGregorianCalendar value) {
        this.dtIncidentCommServ = value;
    }

    /**
     * Gets the value of the strDeclarantCommServ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantCommServ() {
        return strDeclarantCommServ;
    }

    /**
     * Sets the value of the strDeclarantCommServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantCommServ(String value) {
        this.strDeclarantCommServ = value;
    }

    /**
     * Gets the value of the strNomCommServ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNomCommServ() {
        return strNomCommServ;
    }

    /**
     * Sets the value of the strNomCommServ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNomCommServ(String value) {
        this.strNomCommServ = value;
    }

    /**
     * Gets the value of the strCdPN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCdPN() {
        return strCdPN;
    }

    /**
     * Sets the value of the strCdPN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCdPN(String value) {
        this.strCdPN = value;
    }

    /**
     * Gets the value of the strCgPN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCgPN() {
        return strCgPN;
    }

    /**
     * Sets the value of the strCgPN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCgPN(String value) {
        this.strCgPN = value;
    }

    /**
     * Gets the value of the strCreator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCreator() {
        return strCreator;
    }

    /**
     * Sets the value of the strCreator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCreator(String value) {
        this.strCreator = value;
    }

    /**
     * Gets the value of the strPhoneOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrPhoneOwner() {
        return strPhoneOwner;
    }

    /**
     * Sets the value of the strPhoneOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrPhoneOwner(String value) {
        this.strPhoneOwner = value;
    }

    /**
     * Gets the value of the nsubrfid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNSUBRFID() {
        return nsubrfid;
    }

    /**
     * Sets the value of the nsubrfid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNSUBRFID(BigInteger value) {
        this.nsubrfid = value;
    }

    /**
     * Gets the value of the ntownid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNTOWNID() {
        return ntownid;
    }

    /**
     * Sets the value of the ntownid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNTOWNID(BigInteger value) {
        this.ntownid = value;
    }

    /**
     * Gets the value of the ntoponimid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNTOPONIMID() {
        return ntoponimid;
    }

    /**
     * Sets the value of the ntoponimid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNTOPONIMID(BigInteger value) {
        this.ntoponimid = value;
    }

    /**
     * Gets the value of the nraionid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNRAIONID() {
        return nraionid;
    }

    /**
     * Sets the value of the nraionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNRAIONID(BigInteger value) {
        this.nraionid = value;
    }

    /**
     * Gets the value of the ngeonimid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNGEONIMID() {
        return ngeonimid;
    }

    /**
     * Sets the value of the ngeonimid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNGEONIMID(BigInteger value) {
        this.ngeonimid = value;
    }

    /**
     * Gets the value of the strAddressString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrAddressString() {
        return strAddressString;
    }

    /**
     * Sets the value of the strAddressString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrAddressString(String value) {
        this.strAddressString = value;
    }

    /**
     * Gets the value of the strBuilding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrBuilding() {
        return strBuilding;
    }

    /**
     * Sets the value of the strBuilding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrBuilding(String value) {
        this.strBuilding = value;
    }

    /**
     * Gets the value of the strCorps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCorps() {
        return strCorps;
    }

    /**
     * Sets the value of the strCorps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCorps(String value) {
        this.strCorps = value;
    }

    /**
     * Gets the value of the strRoom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrRoom() {
        return strRoom;
    }

    /**
     * Sets the value of the strRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrRoom(String value) {
        this.strRoom = value;
    }

    /**
     * Gets the value of the strAdditionalLocationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrAdditionalLocationInfo() {
        return strAdditionalLocationInfo;
    }

    /**
     * Sets the value of the strAdditionalLocationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrAdditionalLocationInfo(String value) {
        this.strAdditionalLocationInfo = value;
    }

    /**
     * Gets the value of the strEntrance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrEntrance() {
        return strEntrance;
    }

    /**
     * Sets the value of the strEntrance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrEntrance(String value) {
        this.strEntrance = value;
    }

    /**
     * Gets the value of the strEntranceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrEntranceCode() {
        return strEntranceCode;
    }

    /**
     * Sets the value of the strEntranceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrEntranceCode(String value) {
        this.strEntranceCode = value;
    }

    /**
     * Gets the value of the strStoreys property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrStoreys() {
        return strStoreys;
    }

    /**
     * Sets the value of the strStoreys property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrStoreys(String value) {
        this.strStoreys = value;
    }

    /**
     * Gets the value of the strIncidentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrIncidentDescription() {
        return strIncidentDescription;
    }

    /**
     * Sets the value of the strIncidentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrIncidentDescription(String value) {
        this.strIncidentDescription = value;
    }

    /**
     * Gets the value of the nIncidentTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNIncidentTypeID() {
        return nIncidentTypeID;
    }

    /**
     * Sets the value of the nIncidentTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNIncidentTypeID(BigInteger value) {
        this.nIncidentTypeID = value;
    }

    /**
     * Gets the value of the strCallerContactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCallerContactPhone() {
        return strCallerContactPhone;
    }

    /**
     * Sets the value of the strCallerContactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCallerContactPhone(String value) {
        this.strCallerContactPhone = value;
    }

    /**
     * Gets the value of the strDeclarantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantName() {
        return strDeclarantName;
    }

    /**
     * Sets the value of the strDeclarantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantName(String value) {
        this.strDeclarantName = value;
    }

    /**
     * Gets the value of the strDeclarantLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantLastName() {
        return strDeclarantLastName;
    }

    /**
     * Sets the value of the strDeclarantLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantLastName(String value) {
        this.strDeclarantLastName = value;
    }

    /**
     * Gets the value of the strDeclarantMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantMiddleName() {
        return strDeclarantMiddleName;
    }

    /**
     * Sets the value of the strDeclarantMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantMiddleName(String value) {
        this.strDeclarantMiddleName = value;
    }

    /**
     * Gets the value of the strDeclarantBuildingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantBuildingNumber() {
        return strDeclarantBuildingNumber;
    }

    /**
     * Sets the value of the strDeclarantBuildingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantBuildingNumber(String value) {
        this.strDeclarantBuildingNumber = value;
    }

    /**
     * Gets the value of the nDeclarantSUBRFID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNDeclarantSUBRFID() {
        return nDeclarantSUBRFID;
    }

    /**
     * Sets the value of the nDeclarantSUBRFID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNDeclarantSUBRFID(BigInteger value) {
        this.nDeclarantSUBRFID = value;
    }

    /**
     * Gets the value of the nDeclarantTOWNID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNDeclarantTOWNID() {
        return nDeclarantTOWNID;
    }

    /**
     * Sets the value of the nDeclarantTOWNID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNDeclarantTOWNID(BigInteger value) {
        this.nDeclarantTOWNID = value;
    }

    /**
     * Gets the value of the nDeclarantTOPONIMID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNDeclarantTOPONIMID() {
        return nDeclarantTOPONIMID;
    }

    /**
     * Sets the value of the nDeclarantTOPONIMID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNDeclarantTOPONIMID(BigInteger value) {
        this.nDeclarantTOPONIMID = value;
    }

    /**
     * Gets the value of the nDeclarantRAIONID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNDeclarantRAIONID() {
        return nDeclarantRAIONID;
    }

    /**
     * Sets the value of the nDeclarantRAIONID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNDeclarantRAIONID(BigInteger value) {
        this.nDeclarantRAIONID = value;
    }

    /**
     * Gets the value of the nDeclarantGEONIMID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNDeclarantGEONIMID() {
        return nDeclarantGEONIMID;
    }

    /**
     * Sets the value of the nDeclarantGEONIMID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNDeclarantGEONIMID(BigInteger value) {
        this.nDeclarantGEONIMID = value;
    }

    /**
     * Gets the value of the strDeclarantAddressString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantAddressString() {
        return strDeclarantAddressString;
    }

    /**
     * Sets the value of the strDeclarantAddressString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantAddressString(String value) {
        this.strDeclarantAddressString = value;
    }

    /**
     * Gets the value of the strDeclarantCorps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantCorps() {
        return strDeclarantCorps;
    }

    /**
     * Sets the value of the strDeclarantCorps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantCorps(String value) {
        this.strDeclarantCorps = value;
    }

    /**
     * Gets the value of the strDeclarantFlat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDeclarantFlat() {
        return strDeclarantFlat;
    }

    /**
     * Sets the value of the strDeclarantFlat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDeclarantFlat(String value) {
        this.strDeclarantFlat = value;
    }

    /**
     * Gets the value of the geoLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeoLatitude() {
        return geoLatitude;
    }

    /**
     * Sets the value of the geoLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeoLatitude(String value) {
        this.geoLatitude = value;
    }

    /**
     * Gets the value of the geoLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeoLongitude() {
        return geoLongitude;
    }

    /**
     * Sets the value of the geoLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeoLongitude(String value) {
        this.geoLongitude = value;
    }

    /**
     * Gets the value of the declarantGeoLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclarantGeoLatitude() {
        return declarantGeoLatitude;
    }

    /**
     * Sets the value of the declarantGeoLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclarantGeoLatitude(String value) {
        this.declarantGeoLatitude = value;
    }

    /**
     * Gets the value of the declarantGeoLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclarantGeoLongitude() {
        return declarantGeoLongitude;
    }

    /**
     * Sets the value of the declarantGeoLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclarantGeoLongitude(String value) {
        this.declarantGeoLongitude = value;
    }

    /**
     * Gets the value of the callId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallId() {
        return callId;
    }

    /**
     * Sets the value of the callId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallId(String value) {
        this.callId = value;
    }

    /**
     * Gets the value of the strLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrLanguage() {
        return strLanguage;
    }

    /**
     * Sets the value of the strLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrLanguage(String value) {
        this.strLanguage = value;
    }

    /**
     * Gets the value of the lNear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLNear() {
        return lNear;
    }

    /**
     * Sets the value of the lNear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLNear(BigInteger value) {
        this.lNear = value;
    }

    /**
     * Gets the value of the strKm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrKm() {
        return strKm;
    }

    /**
     * Sets the value of the strKm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrKm(String value) {
        this.strKm = value;
    }

    /**
     * Gets the value of the nCasualties property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNCasualties() {
        return nCasualties;
    }

    /**
     * Sets the value of the nCasualties property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNCasualties(BigInteger value) {
        this.nCasualties = value;
    }

    /**
     * Gets the value of the lHumanThreat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLHumanThreat() {
        return lHumanThreat;
    }

    /**
     * Sets the value of the lHumanThreat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLHumanThreat(BigInteger value) {
        this.lHumanThreat = value;
    }

    /**
     * Gets the value of the strCharacter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCharacter() {
        return strCharacter;
    }

    /**
     * Sets the value of the strCharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCharacter(String value) {
        this.strCharacter = value;
    }

    /**
     * Gets the value of the srtCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrtCondition() {
        return srtCondition;
    }

    /**
     * Sets the value of the srtCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrtCondition(String value) {
        this.srtCondition = value;
    }

    /**
     * Gets the value of the nNumberStoreys property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNNumberStoreys() {
        return nNumberStoreys;
    }

    /**
     * Sets the value of the nNumberStoreys property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNNumberStoreys(BigInteger value) {
        this.nNumberStoreys = value;
    }

    /**
     * Gets the value of the nGaz property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNGaz() {
        return nGaz;
    }

    /**
     * Sets the value of the nGaz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNGaz(BigInteger value) {
        this.nGaz = value;
    }

    /**
     * Gets the value of the nTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNTime() {
        return nTime;
    }

    /**
     * Sets the value of the nTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNTime(BigInteger value) {
        this.nTime = value;
    }

    /**
     * Gets the value of the strRepercussion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrRepercussion() {
        return strRepercussion;
    }

    /**
     * Sets the value of the strRepercussion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrRepercussion(String value) {
        this.strRepercussion = value;
    }

    /**
     * Gets the value of the nPeople property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNPeople() {
        return nPeople;
    }

    /**
     * Sets the value of the nPeople property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNPeople(BigInteger value) {
        this.nPeople = value;
    }

}
