//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.05 at 06:19:25 PM MSK 
//


package ru.telda.dds_01_integration_service.soap_service.integration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.telda.dds_01.integration_service.soap_service.integration package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.telda._01.integration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Card112Response }
     * 
     */
    public Card112Response createCard112Response() {
        return new Card112Response();
    }

    /**
     * Create an instance of {@link Card112Result }
     * 
     */
    public Card112Result createCard112Result() {
        return new Card112Result();
    }

    /**
     * Create an instance of {@link ru.telda.dds_01_integration_service.soap_service.integration.Card112 }
     * 
     */
    public ru.telda.dds_01_integration_service.soap_service.integration.Card112 createCard112() {
        return new ru.telda.dds_01_integration_service.soap_service.integration.Card112();
    }

    /**
     * Create an instance of {@link Card112Type }
     * 
     */
    public Card112Type createCard112Type() {
        return new Card112Type();
    }

}
