//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.05 at 06:19:25 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.telda.ru/dds_01_integration_service/soap_service/integration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.telda.dds_01_integration_service.soap_service.integration;
